### ISSUE TITLE
Articles with attached notes causing issue

### ISSUE THREAD

**Issue by nmoran** [samuelyeewl/zotrm#4]
When there is a note attached to an article that is being synched an error is returned from the zotoro API

```pyzotero.zotero_errors.UnsupportedParams: 
Code: 400
URL: https://api.zotero.org/users/XXXXX/items/XXXXX/children?format=json&limit=100
Method: GET
Response: /children cannot be called on note items
```

Removing the note from the item allows this to work but maybe there is a way to skip notes.

**Comment by samuelyeewl** [comment]
Fixed in commit 683c563.
